plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Naming/FileName:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Naming/AccessorMethodName:
  Enabled: false
